services:
  - type: web
    name: smart-travel-ai
    env: docker
    rootDir: recommendation-service
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-3.1-flash-lite
      - key: CORS_ALLOWED_ORIGINS
        sync: false

  - type: web
    name: smart-travel-backend
    env: docker
    rootDir: backend-core
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SPRING_FLYWAY_BASELINE_ON_MIGRATE
        value: "true"
      - key: SPRING_FLYWAY_BASELINE_VERSION
        value: "0"
      - key: COOKIE_SECURE
        value: "true"
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-3.1-flash-lite
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: RECOMMENDATION_SERVICE_URL
        sync: false
